baseURL: https://example.com
googleAnalytics: 
languageCode: en-us
enableEmoji: yes
theme: avicenna
title: Samuel Jens
paginate: 10
markup:
  tableOfContents:
    endLevel: 3
    ordered: no
    startLevel: 1
params:
  name: Samuel Jens
